//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SampleWebsite.Models
{
    public partial class userinfo
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
        public string phoneno { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<short> status { get; set; }
    }
    
}
